#!/usr/bin/env node
// Funding bar for the site: reads what has been donated toward Google's yearly
// security assessment (CASA) from GitHub Sponsors and Buy Me a Coffee, writes
// site/funding.json and renders the bar into site/index.html.
//
// Runs in the site deploy workflow (.github/workflows/deploy-site.yml), on
// every deploy and once a day. There is no server: the totals are read at
// deploy time and published as static files.
//
// Amounts on both platforms are visible to the account owner only, so each
// source needs a token (GH_SPONSORS_TOKEN, BMC_TOKEN). A source without a
// token is reported as "not-configured" and left out of the sum. A source with
// a token whose request fails makes this script exit non-zero AFTER it has
// written the last published values back, so a deploy never shows a wrong
// zero and the failure is still visible in the workflow run.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

export const CONFIG = {
  goalCents: 67500,
  // Donations before this date are not part of the campaign.
  campaignStart: '2026-10-01',
  // The assessment has to start by then; the maintainer pays what is missing.
  backstopDate: '2026-11-02',
  auditDue: '2026-12-29',
  // Subtracted from the sum. Raise it at each yearly renewal to start the next
  // year's bar from zero without losing the history on the platforms.
  baselineCents: 0,
  githubLogin: 'marlinjai',
  // The goal is in US dollars because the lab's invoice is. Donations in
  // another currency are converted with these fixed rates (ECB reference rate
  // of 2026-10-01); an unknown currency is an error, never a silent skip.
  usdPerUnit: { USD: 1, EUR: 1.1298 },
  publishedUrl: 'https://email.lumitra.co/funding.json',
  sponsorsUrl: 'https://github.com/sponsors/marlinjai',
  bmcUrl: 'https://buymeacoffee.com/marlinjai',
};

export const MARK_START = '<!-- funding:start (generated by scripts/funding.mjs, do not edit by hand) -->';
export const MARK_END = '<!-- funding:end -->';

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

/** "2026-11-02" -> "2 November 2026" */
export function formatDate(iso) {
  const [y, m, d] = iso.slice(0, 10).split('-').map(Number);
  return `${d} ${MONTHS[m - 1]} ${y}`;
}

function toUsdCents(amount, currency, usdPerUnit) {
  const rate = usdPerUnit[String(currency || '').toUpperCase()];
  if (rate === undefined) throw new Error(`No conversion rate configured for currency "${currency}"`);
  return Math.round(amount * rate * 100);
}

/** "2026-10-03 14:05:00" or an ISO string, read as UTC when no zone is given. */
function parseUtc(value) {
  const text = String(value).trim().replace(' ', 'T');
  return new Date(/(Z|[+-]\d\d:?\d\d)$/.test(text) ? text : `${text}Z`);
}

function requireNumber(value, field) {
  const n = typeof value === 'string' ? Number(value) : value;
  if (typeof n !== 'number' || !Number.isFinite(n)) {
    throw new Error(`Unexpected response: "${field}" is not a number (${JSON.stringify(value)})`);
  }
  return n;
}

/**
 * GitHub Sponsors: nodes of `viewer.lifetimeReceivedSponsorshipValues`, each
 * the total one sponsor has ever paid. Already in US dollar cents.
 */
export function sumGithub(nodes) {
  if (!Array.isArray(nodes)) throw new Error('Unexpected response: GitHub sponsorship values are not a list');
  let cents = 0;
  let supporters = 0;
  for (const node of nodes) {
    const amount = requireNumber(node?.amountInCents, 'amountInCents');
    if (amount > 0) {
      cents += amount;
      supporters += 1;
    }
  }
  return { cents, supporters };
}

/**
 * Buy Me a Coffee one-time supporters: coffees times price, refunds left out,
 * only from the campaign start on.
 */
export function sumBmcSupporters(supporters, config = CONFIG) {
  if (!Array.isArray(supporters)) throw new Error('Unexpected response: Buy Me a Coffee supporters are not a list');
  let cents = 0;
  let count = 0;
  for (const s of supporters) {
    if (typeof s?.support_created_on !== 'string') {
      throw new Error('Unexpected response: supporter without "support_created_on"');
    }
    if (s.is_refunded) continue;
    if (s.support_created_on.slice(0, 10) < config.campaignStart) continue;
    const amount = requireNumber(s.support_coffees, 'support_coffees') * requireNumber(s.support_coffee_price, 'support_coffee_price');
    cents += toUsdCents(amount, s.support_currency, config.usdPerUnit);
    count += 1;
  }
  return { cents, supporters: count };
}

/**
 * Buy Me a Coffee memberships: one payment per started period since the later
 * of the membership start and the campaign start, up to the cancellation date
 * or now. An approximation of what was actually charged, on the low side for
 * nobody: every counted period has started.
 */
export function sumBmcMemberships(subscriptions, now, config = CONFIG) {
  if (!Array.isArray(subscriptions)) throw new Error('Unexpected response: Buy Me a Coffee memberships are not a list');
  let cents = 0;
  let count = 0;
  for (const sub of subscriptions) {
    if (typeof sub?.subscription_created_on !== 'string') {
      throw new Error('Unexpected response: membership without "subscription_created_on"');
    }
    const created = parseUtc(sub.subscription_created_on);
    const campaignStart = new Date(`${config.campaignStart}T00:00:00Z`);
    const cancelled = sub.subscription_cancelled_on ? parseUtc(sub.subscription_cancelled_on) : null;
    const until = cancelled && cancelled < now ? cancelled : now;
    if (Number.isNaN(created.getTime())) throw new Error('Unexpected response: unreadable membership start date');
    if (until < campaignStart || until < created) continue;
    const yearly = /year/i.test(String(sub.subscription_duration_type || ''));
    const periodMonths = yearly ? 12 : 1;
    // Payments fall on the membership's own anniversaries; count those inside
    // [max(created, campaignStart), until].
    let periods = 0;
    for (let i = 0; i < 1200; i += 1) {
      const charge = new Date(created);
      charge.setUTCMonth(charge.getUTCMonth() + i * periodMonths);
      if (charge > until) break;
      if (charge >= campaignStart) periods += 1;
    }
    if (periods === 0) continue;
    const price = requireNumber(sub.subscription_coffee_price, 'subscription_coffee_price')
      * requireNumber(sub.subscription_coffee_num ?? 1, 'subscription_coffee_num');
    cents += toUsdCents(price * periods, sub.subscription_currency, config.usdPerUnit);
    count += 1;
  }
  return { cents, supporters: count };
}

/** Which of the three texts the bar shows. */
export function phaseFor(collectedCents, now, config = CONFIG) {
  if (collectedCents !== null && collectedCents >= config.goalCents) return 'reached';
  return now.toISOString().slice(0, 10) >= config.backstopDate ? 'backstopped' : 'collecting';
}

/**
 * @param {{ github: {status: string, cents?: number, supporters?: number},
 *           bmc: {status: string, cents?: number, supporters?: number},
 *           now: Date, config?: typeof CONFIG }} input
 */
export function buildState({ github, bmc, now, config = CONFIG }) {
  const connected = [github, bmc].filter((s) => s.status === 'ok');
  const collectedCents = connected.length === 0
    ? null
    : Math.max(0, connected.reduce((sum, s) => sum + s.cents, 0) - config.baselineCents);
  const supporters = connected.reduce((sum, s) => sum + s.supporters, 0);
  return {
    goalCents: config.goalCents,
    collectedCents,
    supporters,
    phase: phaseFor(collectedCents, now, config),
    updatedAt: now.toISOString(),
    period: { start: config.campaignStart, backstop: config.backstopDate, auditDue: config.auditDue },
    sources: { githubSponsors: github.status, buyMeACoffee: bmc.status },
  };
}

function dollars(cents) {
  const whole = cents / 100;
  return Number.isInteger(whole) ? String(whole) : whole.toFixed(2);
}

const PHASE_NOTE = {
  collecting: (s) => `Collecting until ${formatDate(s.period.backstop)}, the day the assessment has to start. Whatever is missing then, the maintainer pays.`,
  backstopped: (s) => `The assessment had to start on ${formatDate(s.period.backstop)}, so the maintainer covers what is missing. Donations still count toward this year's fee and next year's renewal.`,
  reached: () => 'Goal reached, thank you. Anything above it goes toward next year\'s assessment.',
};

/** The HTML that goes between the markers in site/index.html. */
export function renderBlock(state, config = CONFIG) {
  const goal = dollars(state.goalCents);
  const note = PHASE_NOTE[state.phase](state);
  const links = `<div class="cta-row">
      <a class="cta ghost" href="${config.sponsorsUrl}">Sponsor on GitHub</a>
      <a class="cta ghost" href="${config.bmcUrl}">Buy Me a Coffee</a>
    </div>`;
  if (state.collectedCents === null) {
    return `<div class="fund" id="funding">
      <p class="fund-title"><strong>Goal: ${goal} US dollars</strong> for this year's Google security assessment</p>
      <p class="fund-note">The amount collected so far is not connected to this page yet. ${note}</p>
    </div>
    ${links}`;
  }
  const collected = dollars(state.collectedCents);
  const percent = Math.min(100, Math.floor((state.collectedCents / state.goalCents) * 100));
  const stale = state.stale ? ' The donation platforms could not be reached at the last update, so this is the last known amount.' : '';
  const partial = Object.values(state.sources).includes('not-configured')
    ? ' One of the two donation platforms is not connected yet, so the real amount may be higher.'
    : '';
  const people = state.supporters === 1 ? '1 supporter' : `${state.supporters} supporters`;
  return `<div class="fund" id="funding">
      <p class="fund-title"><strong>${collected} of ${goal} US dollars</strong> collected for this year's Google security assessment</p>
      <progress class="fund-bar" max="${state.goalCents}" value="${Math.min(state.collectedCents, state.goalCents)}" aria-label="Collected toward the yearly security assessment">${percent} percent</progress>
      <p class="fund-note">${people}, ${percent} percent of the goal. ${note}${partial}${stale} Updated ${formatDate(state.updatedAt)}, refreshed once a day.</p>
    </div>
    ${links}`;
}

/** Replaces what is between the markers. Throws if the markers are missing. */
export function inject(html, block) {
  const start = html.indexOf(MARK_START);
  const end = html.indexOf(MARK_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error('Funding markers not found in the page; the bar cannot be rendered');
  }
  return `${html.slice(0, start + MARK_START.length)}\n    ${block}\n    ${html.slice(end)}`;
}

// ---- network (thin; the logic above is what the tests cover) ----

async function fetchGithub(token, config) {
  const nodes = [];
  let after = null;
  for (let page = 0; page < 50; page += 1) {
    const res = await fetch('https://api.github.com/graphql', {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', 'User-Agent': 'email-mcp-funding' },
      body: JSON.stringify({
        query: `query($after: String) { viewer { login lifetimeReceivedSponsorshipValues(first: 100, after: $after) {
          nodes { amountInCents } pageInfo { hasNextPage endCursor } } } }`,
        variables: { after },
      }),
    });
    if (!res.ok) throw new Error(`GitHub Sponsors: HTTP ${res.status}`);
    const body = await res.json();
    if (body.errors?.length) throw new Error(`GitHub Sponsors: ${body.errors[0].message}`);
    const viewer = body.data?.viewer;
    // Amounts are only visible to the account that receives them. A token of
    // any other account would read an empty list and look like zero donations.
    if (viewer?.login !== config.githubLogin) {
      throw new Error(`GitHub Sponsors: the token belongs to "${viewer?.login}", expected "${config.githubLogin}"`);
    }
    const values = viewer.lifetimeReceivedSponsorshipValues;
    nodes.push(...(values?.nodes ?? []));
    if (!values?.pageInfo?.hasNextPage) return sumGithub(nodes);
    after = values.pageInfo.endCursor;
  }
  throw new Error('GitHub Sponsors: more than 50 pages of sponsors, refusing to guess');
}

async function fetchBmcList(token, resource) {
  const items = [];
  for (let page = 1; page <= 200; page += 1) {
    const res = await fetch(`https://developers.buymeacoffee.com/api/v1/${resource}?page=${page}`, {
      headers: { Authorization: `Bearer ${token}`, Accept: 'application/json', 'User-Agent': 'email-mcp-funding' },
    });
    if (!res.ok) throw new Error(`Buy Me a Coffee ${resource}: HTTP ${res.status}`);
    const body = await res.json();
    // An account without any entry answers with an error string, not a list.
    if (typeof body.error === 'string' && /^no /i.test(body.error)) return items;
    if (!Array.isArray(body.data)) throw new Error(`Buy Me a Coffee ${resource}: unexpected response shape`);
    items.push(...body.data);
    if (!body.next_page_url || page >= (body.last_page ?? page)) return items;
  }
  throw new Error(`Buy Me a Coffee ${resource}: more than 200 pages, refusing to guess`);
}

async function fetchBmc(token, now, config) {
  const one = sumBmcSupporters(await fetchBmcList(token, 'supporters'), config);
  const members = sumBmcMemberships(await fetchBmcList(token, 'subscriptions'), now, config);
  return { cents: one.cents + members.cents, supporters: one.supporters + members.supporters };
}

async function readSource(name, token, read) {
  if (!token) {
    console.log(`::notice::${name}: no token configured, left out of the funding bar`);
    return { status: 'not-configured' };
  }
  const result = await read(token);
  return { status: 'ok', ...result };
}

async function main() {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const pagePath = path.join(root, 'site', 'index.html');
  const jsonPath = path.join(root, 'site', 'funding.json');
  const now = new Date();
  let state;
  let failure = null;
  try {
    const github = await readSource('GitHub Sponsors', process.env.GH_SPONSORS_TOKEN, (t) => fetchGithub(t, CONFIG));
    const bmc = await readSource('Buy Me a Coffee', process.env.BMC_TOKEN, (t) => fetchBmc(t, now, CONFIG));
    state = buildState({ github, bmc, now });
  } catch (err) {
    failure = err;
    console.log(`::error::Funding bar: ${err.message}`);
    // Keep what is published instead of showing a wrong amount.
    try {
      const res = await fetch(CONFIG.publishedUrl, { headers: { 'User-Agent': 'email-mcp-funding' } });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const published = await res.json();
      if (typeof published.goalCents !== 'number') throw new Error('not a funding file');
      state = {
        ...published,
        phase: phaseFor(published.collectedCents, now),
        stale: published.collectedCents !== null,
      };
      console.log('Reusing the last published amount.');
    } catch (reuseErr) {
      console.log(`No published amount to reuse (${reuseErr.message}); showing the goal only.`);
      state = buildState({ github: { status: 'not-configured' }, bmc: { status: 'not-configured' }, now });
    }
  }
  const html = await readFile(pagePath, 'utf8');
  await writeFile(pagePath, inject(html, renderBlock(state)));
  await writeFile(jsonPath, `${JSON.stringify(state, null, 2)}\n`);
  console.log(`Funding bar: ${state.collectedCents === null ? 'not connected' : `${dollars(state.collectedCents)} of ${dollars(state.goalCents)} US dollars`} (${state.phase})`);
  if (failure) process.exit(1);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.log(`::error::Funding bar: ${err.message}`);
    process.exit(1);
  });
}
